version: "2"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: wu_zookeeper
    ports:
      - "2181"
    restart: "unless-stopped"
  kafka:
    image: wurstmeister/kafka
    container_name: wu_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.101
      KAFKA_ZOOKEEPER_CONNECT: wu_zookeeper:2181
    restart: "unless-stopped"